### ISSUE TITLE
Is it possible to make this mod optional on the client?

### ISSUE THREAD

**Issue by BinarMorker** [CriochDev/FIFYM-Custom-Crafting#23]

**Comment by ChrqnosMC** [comment]
we would especially like to know if it would be possible to have only the item components that can be used in custom crafts without necessarily having the new item components that you added.

**Comment by CriochDev** [comment]
Unfortunately, due to how mojang's crafting system is set up it is required on both client and server.

Are you asking for a version without the item components I've added?

**Comment by BinarMorker** [comment]
Well yes, the idea would have been to allow for custom crafting recipes on servers using existing item components only, while allowing vanilla clients to connect.

**Comment by ChrqnosMC** [comment]
a version without the new components could be interesting yes

I'd also like to take this opportunity to suggest an idea, even if it's not really in keeping with the theme of the mods, but could making item components usable with tags be an idea that might interest you?

**Comment by ChrqnosMC** [comment]
so is it possible to have a version without the added component items, or is that not possible?

**Comment by CriochDev** [comment]
Sorry, I'm not interested in making this a server-only mod. I really don't have the time to manage two different versions at the moment.
