### ISSUE TITLE
"Base" item in smithing recipe consumed regardless of fifymcc:recipe_remainder component on item.

### ISSUE THREAD

**Issue by dod-funk** [CriochDev/FIFYM-Custom-Crafting#24]
I discovered that the 'base' item in the 'smithing_transform' recipe gets consumed regardless of any of the 'fifymcc:recipe_remainder' components on it. I've tried it with the 'damaged' & 'unconsumed' components.

![1Stone_Hammer_Components](https://github.com/user-attachments/assets/64f14331-0cc6-4dd0-af79-837205a58de7)
![2Stone_Axe_Components](https://github.com/user-attachments/assets/96728b17-f3d7-4495-81be-07ac8e8a16fb)
![3Recipe_in_Smithing_Table](https://github.com/user-attachments/assets/7b1e46b8-a3f0-459d-a0eb-2e11ccbc5237)
![4Recipe_Crafted](https://github.com/user-attachments/assets/da2bd8d6-5fbc-44e7-bcca-964cfedf0cf3)

**Comment by CriochDev** [comment]
Alrighty, I'll get this fixed

**Comment by CriochDev** [comment]
Would you mind providing the recipe that you are using?

**Comment by CriochDev** [comment]
OH! You're doing a smithing recipe. As the smithing recipes do not actually consume the base ingredient and instead use it as the base for the output, I made it so it specifically does not apply to the base ingredient. Basically, it's working as intended.

**Comment by dod-funk** [comment]
I see, no worries. Thank you for looking into that!
